### ISSUE TITLE
FR-Net architecture

### ISSUE THREAD

**Issue by cs123951** [bknyaz/emotiw#2]
Hi, I have read your paper. But I don't know what the net architecture of FR-Net-A, FR-Net-B and FR-Net-C are?
Could you give some details about these three net? For example, the number of data layers and so on.

**Comment by bknyaz** [comment]
Hi, unfortunately I can't make the architectures available or provide any additional details about training the networks, because those are proprietary networks. I would suggest to try different state of the art networks in image classification to achieve similar performance. 
I can only help with running the code in this repository.
